# CIPHER Platform - Cloud Build Configuration
# Automated build and deployment pipeline

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/telegram-ai-processor:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/telegram-ai-processor:latest',
      '.'
    ]
    id: 'build-image'

  # Step 2: Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/telegram-ai-processor:$BUILD_ID'
    ]
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/telegram-ai-processor:latest'
    ]
    id: 'push-latest'
    waitFor: ['build-image']

  # Step 4: Setup BigQuery dataset and permissions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Enable APIs
        gcloud services enable bigquery.googleapis.com run.googleapis.com
        
        # Create BigQuery dataset if it doesn't exist
        bq ls --project_id=$PROJECT_ID telegram_data || \
        bq mk --dataset --location=US --description="CIPHER Intelligence Data" $PROJECT_ID:telegram_data
        
        # Set up service account permissions
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:cipher-service@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/bigquery.admin" --quiet || true
        
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:cipher-service@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/bigquery.jobUser" --quiet || true
        
        echo "BigQuery setup completed"
    id: 'setup-bigquery'

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'telegram-ai-processor',
      '--image', 'gcr.io/$PROJECT_ID/telegram-ai-processor:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--service-account', 'cipher-service@$PROJECT_ID.iam.gserviceaccount.com',
      '--memory', '4Gi',
      '--cpu', '2',
      '--timeout', '3600',
      '--max-instances', '10',
      '--min-instances', '0',
      '--port', '8080',
      '--concurrency', '80',
      '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,LOG_LEVEL=INFO,DATASET_ID=telegram_data,TABLE_ID=processed_messages,PORT=8080,PYTHONUNBUFFERED=1'
    ]
    id: 'deploy-cloud-run'
    waitFor: ['push-image', 'setup-bigquery']

  # Step 6: Health check
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get service URL
        SERVICE_URL=$(gcloud run services describe telegram-ai-processor \
          --region=us-central1 --format='value(status.url)')
        
        echo "Service URL: $SERVICE_URL"
        
        # Wait a bit for service to be ready
        sleep 30
        
        # Test health endpoints
        echo "Testing health endpoints..."
        curl -f "$SERVICE_URL/health/live" || exit 1
        curl -f "$SERVICE_URL/health" || exit 1
        
        echo "✅ CIPHER Platform deployment successful!"
        echo "Dashboard: $SERVICE_URL/dashboard"
    id: 'health-check'
    waitFor: ['deploy-cloud-run']

# Build configuration
options:
  # Use higher performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Enable logging
  logging: CLOUD_LOGGING_ONLY
  
  # Set substitutions
  substitution_option: 'ALLOW_LOOSE'

# Timeout for the entire build
timeout: '1200s'

# Images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/telegram-ai-processor:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/telegram-ai-processor:latest'

# Substitutions (can be overridden)
substitutions:
  _SERVICE_NAME: 'telegram-ai-processor'
  _REGION: 'us-central1'
