apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: telegram-ai-processor
  namespace: 'primal-chariot-382610'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: cloud-build-service@primal-chariot-382610.iam.gserviceaccount.com
      containers:
      - image: gcr.io/primal-chariot-382610/telegram-ai-processor:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: primal-chariot-382610
        - name: WEBHOOK_URL
          value: https://telegram-ai-processor-[HASH]-uc.a.run.app
        - name: TELEGRAM_SECRET_TOKEN
          value: your-webhook-secret-token
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
